import React from 'react';

interface PreviewProps {
  files: { [key: string]: string };
}

const Preview: React.FC<PreviewProps> = ({ files }) => {
  const code = files['App.js'] || '';
  
  // A unique key is used to force React to re-mount the component when the code changes.
  // This helps ensure the third-party Expo Snack script re-initializes with the new code.
  const snackKey = React.useMemo(() => `snack-${Date.now()}`, [code]);

  return (
    <div key={snackKey} className="w-full h-full">
        <div
            data-snack-platform="web"
            data-snack-preview="true"
            data-snack-theme="light"
            data-snack-loading="lazy"
            data-snack-name="React Native Preview"
            data-snack-description="A React Native app generated by AI."
            data-snack-code={code}
            data-snack-dependencies="expo-constants,@expo/vector-icons"
            style={{
                overflow: 'hidden',
                background: '#fafafa',
                border: '1px solid rgba(0,0,0,.08)',
                height: '100%',
                width: '100%',
            }}
        ></div>
    </div>
  );
};

export default Preview;
